[advisories]
yanked = "deny"
ignore = []

[licenses]
unused-allowed-license = "allow"
private.ignore = true
allow = [
  "Unlicense",
  "MIT",
  "Apache-2.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
